### PR TITLE
Create wop_schema.xml

### PR DESCRIPTION
**Pull request by KarlenS**
Starting file for database schema.

### CODE REVIEW

**Comment by joshRamirez** [comment]
Hey Karlen, what are the pros/cons of using this schema strategy vs writing out the SQL statements for setting up our databases?

**Comment by KarlenS** [comment]
Hey Josh,

Albert and I are working together to build up the schema. Albert suggested using this tool for mocking it up and coordinating:
https://ondras.zarovi.cz/sql/demo/

It's decent and can output both xml schema and SQL commands (we went with xml originally). There are probably some pros/cons, but for our case, the main timesuck is manually translating a giant pdf document to a bunch of SQL tables. Honestly, I'll probably do most of it with SQL since that's easier to me. For the actual database setup, don't think it matters much - we can bulk import either format.

**Comment by joshRamirez** [comment]
Gotcha. That is an interesting tool. I have never seen it or used it so I have no knowledge on it.  @AlbertUlysses Would you happen to know the pros/cons of this schema strategy?

I was not aware that the different DBs could accept XML. (I learn something new everyday!)(but also I saw the changelog, and it said that v1.x XSLT is not compatible with v2 of the tool you posted, so I think we may want to stay away from that in case the backwards compatibility breaks again)

**Comment by AlbertUlysses** [comment]
The website is a real cool way to create a schema without writing code in the planning phase, it's fast and allows us as a group to make models without migrating back and fourth. I also like it since people on team don't have to download a certain software to view how the schema looks -just upload the XML text and they're set. @joshRamirez  you should check it out, it's pretty intuitive. 
As for the XML thing, the website has an option to out put the schema into a MYSQL script so I don't know if a database actually uses XML! I can show you how to use it tomorrow if you like

**Comment by joshRamirez** [comment]
Sounds good! I will have to look into it myself a bit more tomorrow. It definitely has its a place, I just do not have any of the knowledge of the tool and am thus playing the role a skeptic :)

**Pull request merged**
